services:
  pz_srv:
    image: indifferentbroccoli/projectzomboid-server-docker
    container_name: projectzomboid_b42
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    env_file:
      - .env
    environment:
      GENERATE_SETTINGS: "true"
    volumes:
      - ./server-files:/project-zomboid
      - ./server-data:/project-zomboid-config
